import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1719829505940 implements MigrationInterface {
    name = 'AutoGeneratedMigration1719829505940'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedDate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedAt" DROP NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedDate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "createdAt" SET NOT NULL`);
    }

}
