import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1719829260270 implements MigrationInterface {
    name = 'AutoGeneratedMigration1719829260270'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "salary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "orgId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "serialNo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "createdBy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedTime" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedBy" DROP NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedBy" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "updatedTime" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "createdBy" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "serialNo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "orgId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "salary" SET NOT NULL`);
    }

}
